@ModularMonolith.APIs_HostAddress = https://localhost:7248

### Get all currencies
GET {{ModularMonolith.APIs_HostAddress}}/currencies/
Accept: application/json

### Update Currency Value

PUT {{ModularMonolith.APIs_HostAddress}}/currencies/
Content-Type: application/json

{
  "currencyName": "USD",
  "valueInEuro": 0.85
}

### Get all games

GET {{ModularMonolith.APIs_HostAddress}}/games/
Accept: application/json


###

GET {{ModularMonolith.APIs_HostAddress}}/publishers

###

POST {{ModularMonolith.APIs_HostAddress}}/shopping
Content-Type: application/json


###

GET {{ModularMonolith.APIs_HostAddress}}/shopping/1005
Acctept: application/json




###

GET {{ModularMonolith.APIs_HostAddress}}/publishers/1

###

GET {{ModularMonolith.APIs_HostAddress}}/currencies

###

POST {{ModularMonolith.APIs_HostAddress}}/games
Content-Type: application/json

{
  "minAmount": 0,
  "maxAmount": 100,
  "includePublisher": false
}

###
