// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularMonolithBoundedContexts.BoardGames.Infra;

#nullable disable

namespace ModularMonolithMigrations.BoardGames
{
    [DbContext(typeof(GamesDb))]
    [Migration("20250616121211_BoardGamesInit")]
    partial class BoardGamesInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("games")
                .HasAnnotation("ProductVersion", "10.0.0-preview.5.25277.114")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.BoardGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2147483647);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(1);

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483646)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.ComplexProperty<Dictionary<string, object>>("Price", "ModularMonolithBoundedContexts.BoardGames.Entities.BoardGame.Price#Money", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(4,2)")
                                .HasColumnOrder(2);

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnOrder(3);
                        });

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Games", "games");
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)")
                        .HasColumnOrder(3);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2147483647);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(2);

                    b.Property<int?>("PublisherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483646)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PublisherId");

                    b.ToTable("Contact", "games");
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.GameImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("ImageLocation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2147483647);

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483646)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("GameImage", "games");
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2147483647);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483646)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasAlternateKey("Name");

                    b.ToTable("Publishers", "games");
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.BoardGame", b =>
                {
                    b.HasOne("ModularMonolithBoundedContexts.BoardGames.Entities.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.Contact", b =>
                {
                    b.HasOne("ModularMonolithBoundedContexts.BoardGames.Entities.Publisher", null)
                        .WithMany("Contacts")
                        .HasForeignKey("PublisherId");
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.GameImage", b =>
                {
                    b.HasOne("ModularMonolithBoundedContexts.BoardGames.Entities.BoardGame", null)
                        .WithOne("Image")
                        .HasForeignKey("ModularMonolithBoundedContexts.BoardGames.Entities.GameImage", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.BoardGame", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();
                });

            modelBuilder.Entity("ModularMonolithBoundedContexts.BoardGames.Entities.Publisher", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
