global using ModularMonolithBoundedContexts.Currencies.CommandHandlers;
global using ModularMonolithBoundedContexts.Currencies.Commands;
global using ModularMonolithBoundedContexts.Currencies.DI;
global using ModularMonolithBoundedContexts.Currencies.DomainEventHandlers;
global using ModularMonolithBoundedContexts.Currencies.DomainEvents;
global using ModularMonolithBoundedContexts.Currencies.Entities;
global using ModularMonolithBoundedContexts.Currencies.Infra;
global using ModularMonolithBoundedContexts.Currencies.IntegrationEvents;
global using ModularMonolithBoundedContexts.Currencies.Queries;
global using ModularMonolithBoundedContexts.Currencies.QueryHandlers;
global using ModularMonolithBoundedContexts.Currencies.Repositories;
global using ModularMonolithBoundedContexts.Currencies.ValueObjects;

