global using ModularMonolithBoundedContexts.BoardGames.ValueObjects;
global using ModularMonolithBoundedContexts.BoardGames.Entities;
global using ModularMonolithBoundedContexts.BoardGames.Commands;
global using ModularMonolithBoundedContexts.BoardGames.Repositories;
global using ModularMonolithBoundedContexts.BoardGames.Specifications;
global using ModularMonolithBoundedContexts.BoardGames.IntegrationEvents;
global using ModularMonolithBoundedContexts.BoardGames.Queries;
global using ModularMonolithBoundedContexts.BoardGames.QueryHandlers;
global using ModularMonolithBoundedContexts.BoardGames.Infra;
global using ModularMonolithBoundedContexts.BoardGames.DI;
global using ModularMonolithBoundedContexts.BoardGames.CommandHandlers;


