// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularMonolith.APIs.BoundedContexts.Currencies.Infra;

#nullable disable

namespace ModularMonolith.APIs.Migrations.Currencies
{
    [DbContext(typeof(CurrenciesDb))]
    [Migration("20260318090436_OutboxPatternAgain")]
    partial class OutboxPatternAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("currencies")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModularMonolith.APIs.BoundedContexts.Currencies.Entities.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2147483647);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483646)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("ValueInEuro")
                        .HasColumnType("decimal(18,4)")
                        .HasColumnOrder(2);

                    b.HasKey("Id");

                    b.ToTable("Currencies", "currencies", t =>
                        {
                            t.HasCheckConstraint("CK_Value_Positive", "ValueInEuro > 0");
                        });
                });

            modelBuilder.Entity("ModularMonolith.APIs.EFCore.OutboxPattern.OutboxMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcProcessed")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("UtcProcessed");

                    b.ToTable("Outbox", "currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
