namespace ModularMonolith.APIs.BoundedContexts.BoardGames.Infra;

public sealed partial class GamesDb 
: DbContext
{
  public const string SchemaName = "games";
  public const string DatabaseName = "mm-games-db";

  // Not needed because Source Generated by MintPlayer.SourceGenerators
  //public GamesDb() : base() { }

  //public GamesDb(DbContextOptions<GamesDb> options)
  //    : base(options) { }

  // Only aggregate root entities are registered in the DbSet properties.
  public DbSet<BoardGame> Games => Set<BoardGame>();
  public DbSet<Publisher> Publishers => Set<Publisher>();

  protected override void OnModelCreating(ModelBuilder modelBuilder)
  {
    base.OnModelCreating(modelBuilder);
    modelBuilder.HasDefaultSchema(GamesDb.SchemaName);
    modelBuilder.ApplyConfiguration(new BoardGameConfiguration())
                .ApplyConfiguration(new GameImageConfiguration())
                .ApplyConfiguration(new PublisherConfiguration())
                .ApplyConfiguration(new ContactConfiguration())
                ;
  }

  protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
  {
    configurationBuilder.ConfigureValueObjectValueConverters();
    configurationBuilder.ConfigureBoardGameValueObjectValueConverters();
  }
}