// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModularMonolith.APIs.BoundedContexts.Shopping.Infra;

#nullable disable

namespace ModularMonolith.APIs.Migrations.Shopping
{
    [DbContext(typeof(ShoppingDb))]
    partial class ShoppingDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("shopping")
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.BasketItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BoardGameId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int?>("ShoppingBasketId")
                        .HasColumnType("int");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "ModularMonolith.APIs.BoundedContexts.Shopping.Entities.BasketItem.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(4,2)")
                                .HasColumnOrder(2);

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("nvarchar(3)")
                                .HasColumnOrder(3);
                        });

                    b.HasKey("Id");

                    b.HasIndex("ShoppingBasketId");

                    b.ToTable("BasketItems", "shopping");
                });

            modelBuilder.Entity("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2147483647);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnOrder(2);

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483646)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "ModularMonolith.APIs.BoundedContexts.Shopping.Entities.Customer.Address#Address", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("nvarchar(128)")
                                .HasColumnOrder(4);

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnOrder(3);
                        });

                    b.HasKey("Id");

                    b.ToTable("Customers", "shopping");
                });

            modelBuilder.Entity("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.ShoppingBasket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnOrder(2147483647);

                    b.Property<DateTime>("UtcCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483645)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("UtcDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483646)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("UtcModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnOrder(2147483644)
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("ShoppingBaskets", "shopping");
                });

            modelBuilder.Entity("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.BasketItem", b =>
                {
                    b.HasOne("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.ShoppingBasket", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingBasketId");
                });

            modelBuilder.Entity("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.Customer", b =>
                {
                    b.HasOne("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.ShoppingBasket", null)
                        .WithOne("Customer")
                        .HasForeignKey("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.Customer", "Id");
                });

            modelBuilder.Entity("ModularMonolith.APIs.BoundedContexts.Shopping.Entities.ShoppingBasket", b =>
                {
                    b.Navigation("Customer");

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
