global using ModularMonolithBoundedContexts.BoardGames.ValueObjects;
global using ModularMonolithBoundedContexts.BoardGames.Entities;
global using ModularMonolithBoundedContexts.BoardGames.Commands;
global using ModularMonolithBoundedContexts.BoardGames.Repositories;
global using ModularMonolithBoundedContexts.BoardGames.Specifications;
global using ModularMonolithBoundedContexts.BoardGames.IntegrationEvents;
global using ModularMonolithBoundedContexts.BoardGames.Queries;
global using ModularMonolithBoundedContexts.BoardGames.Infra;
global using ModularMonolithBoundedContexts.Shopping.ValueObjects;
global using ModularMonolithBoundedContexts.Shopping.Entities;
global using ModularMonolithBoundedContexts.Shopping.DomainEvents;
global using ModularMonolithBoundedContexts.Shopping.DI;



